phdoom [options]*

Options:
-2                        Pixel double window.
-3                        Pixel triple window.
-4                        Pixel quadruple window(doesn't currently work right).
-altdeath                 Enable alternate deathmatch mode
-avg                      Same as -timer 20
-config file              Use this config file instead of $HOME/.doomrc.
-deathmatch               Set rules for a multiplayer deathmatch.
-devparm                  Puts you in developers mode.
-disp displayname         Attach to this Photon server.
-dup                      Duplicate tic cammands.
-episode episode          Start at episode 1 to 3. Shareware only has 1.
-extratic                 Provide extra data in each data packet.
-fast                     Make the monsters fast as in nightmare mode.
-file file.wad            Include an external wad file.
-loadgame slot            Load saved game from slot 0 to 5.
-maxdemo size             Specifies the maximum size of a LMP recording.
-net player# host ...     Network multiplayer using TCP/IP Socket manager.
-nomonsters               Don't create any monsters. Usefull for deathmatchs.
-novert                   Ignore mouse y-axis
-playdemo file            Play the demo (default).
-port                     Specify a different IP port (default: 5029).
-record file              Makes a demo recording until you finish or die.
-respawn                  Respawn all monsters 8 seconds after you kill them.
-skill level              Set skill from 1 (baby) to 5 (nightmare).
-ticksize ms              Specify system ticksize (default: 2)
-timedemo file            Calculates the number of times the screen is
                          redrawn when playing a demo
-timer min                Exit level after a number of minutes
-turbo scale              Run faster. Scale can be 10 to 400 percent.
-warp episode level       Warp to episode (1-3) level (1-9)
